# this is name of the workflow that will be displayed in the Actions Tab
name: ci/cd
on:
  workflow_dispatch:
    inputs:
      environments:
        description: this is a env that trigger workflow
        default: 'dev'
        required: true 
        type: choice
        options:
          - dev
          - prod
          - depl
  push:
    paths: '**.yml'
jobs:
  code:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        run: echo "code_check"
  test:
    needs: code
    runs-on: ubuntu-latest
    steps:
      - name: testing contsiner
        run: echo " testing contsiner"
  deploy:
     if: inputs.environments == 'dev' 
     needs: test
     runs-on: ubuntu-latest
     steps:
       - name: deploying contsiner
         run: echo "deployed"


















