# this is name of the workflow that will be displayed in the Actions Tab

name: CICD
on:
  workflow_dispatch:
jobs:
   code:
      runs-on: ubuntu-latest
      steps:
        - name: "checkout code"
          run: echo "code clone"
   test:
     needs: code
     runs-on: ubuntu-latest
     steps:
       - name: "testing"
         run: echo " testing"
   deploy:
     needs: test  
     runs-on: ubuntu-latest
     steps:
       - name: "deploying"
         run: echo "testing"




















