name: hello
on:
  push:
    branches: [main]

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: say hello to users
        run: echo "Hello zaid"

      - name: say hello to username
        run: echo "Hello $USER"
